# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   twitter.client:
      class: Abraham\TwitterOAuth\TwitterOAuth
      arguments:
        - "%twitter.consumer_key%"
        - "%twitter.consumer_secret%"
        - "%twitter.access_token%"
        - "%twitter.access_token_secret%"
   twitter.tweets_importer:
      class: AppBundle\Infrastructure\TweetsImporter
      arguments:
        - "@twitter.client"
   twitter.tweets_persister:
      class: AppBundle\Infrastructure\TweetsPersister
      arguments:
        - "@doctrine.odm.mongodb.document_manager"
