# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twitter_client:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments:
          - "%twitter.api_key%"
          - "%twitter.api_secret%"
          - "%twitter.access_token%"
          - "%twitter.access_token_secret%"
